version: "3.8"

services:
  frontend:
    container_name: frontend
    image: node:18.13.0-alpine
    ports:
      - '3000:3000'
    working_dir: '/source'
    volumes:
      - .:/source
    command: "sh -c 'npm install && npm run dev'"
    networks:
      - default
    restart: always
